language: c

before_install:
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get update -qq
    - sudo apt-get install -y gcc-4.8 libstdc++6 valgrind expect xterm
    - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 50
    - wget https://www.kernel.org/pub/tools/crosstool/files/bin/x86_64/4.8.0/x86_64-gcc-4.8.0-nolibc_powerpc64-linux.tar.xz
    - sudo mkdir /opt/cross
    - sudo tar -C /opt/cross -xvf x86_64-gcc-4.8.0-nolibc_powerpc64-linux.tar.xz
    - wget ftp://public.dhe.ibm.com/software/server/powerfuncsim/p8/packages/v1.0-2/systemsim-p8_1.0-2_amd64.deb
    - sudo dpkg -i systemsim-p8_1.0-2_amd64.deb

env:
    global:
        - CROSS=/opt/cross/gcc-4.8.0-nolibc/powerpc64-linux/bin/powerpc64-linux-
        - HOSTCC=gcc-4.8

script:
    - make && make check
